// Interface automatically generated by schemas-to-ts

import { Media } from '../components/shared/Media';
import { Seo } from '../components/shared/Seo';
import { Media_Plain } from '../components/shared/Media';
import { Seo_Plain } from '../components/shared/Seo';
import { Seo_NoRelations } from '../components/shared/Seo';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Global {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    siteName: string;
    favicon?: { data: Media };
    siteDescription: string;
    defaultSeo?: Seo;
    desktopLogoDark?: { data: Media };
    desktopLogoLight?: { data: Media };
    mobileLogoDark?: { data: Media };
    mobileLogoLight?: { data: Media };
    footerLogo?: { data: Media };
  };
}
export interface Global_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  siteName: string;
  favicon?: Media_Plain;
  siteDescription: string;
  defaultSeo?: Seo_Plain;
  desktopLogoDark?: Media_Plain;
  desktopLogoLight?: Media_Plain;
  mobileLogoDark?: Media_Plain;
  mobileLogoLight?: Media_Plain;
  footerLogo?: Media_Plain;
}

export interface Global_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  siteName: string;
  favicon?: number;
  siteDescription: string;
  defaultSeo?: Seo_NoRelations;
  desktopLogoDark?: number;
  desktopLogoLight?: number;
  mobileLogoDark?: number;
  mobileLogoLight?: number;
  footerLogo?: number;
}

export interface Global_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  siteName: string;
  favicon?: AdminPanelRelationPropertyModification<Media_Plain>;
  siteDescription: string;
  defaultSeo?: Seo_Plain;
  desktopLogoDark?: AdminPanelRelationPropertyModification<Media_Plain>;
  desktopLogoLight?: AdminPanelRelationPropertyModification<Media_Plain>;
  mobileLogoDark?: AdminPanelRelationPropertyModification<Media_Plain>;
  mobileLogoLight?: AdminPanelRelationPropertyModification<Media_Plain>;
  footerLogo?: AdminPanelRelationPropertyModification<Media_Plain>;
}
