// Interface automatically generated by schemas-to-ts

export enum Size {
  Large = 'large',
  Medium = 'medium',
  Small = 'small',}

export interface Module {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    description?: string;
    slug: string;
    default?: boolean;
    size?: Size;
  };
}
export interface Module_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  slug: string;
  default?: boolean;
  size?: Size;
}

export interface Module_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  slug: string;
  default?: boolean;
  size?: Size;
}

export interface Module_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  slug: string;
  default?: boolean;
  size?: Size;
}
