// Interface automatically generated by schemas-to-ts

export interface Test {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Title?: string;
    Description?: any;
    Color?: any;
    headervideo?: any;
    pickcountry?: any;
  };
}
export interface Test_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title?: string;
  Description?: any;
  Color?: any;
  headervideo?: any;
  pickcountry?: any;
}

export interface Test_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title?: string;
  Description?: any;
  Color?: any;
  headervideo?: any;
  pickcountry?: any;
}

export interface Test_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title?: string;
  Description?: any;
  Color?: any;
  headervideo?: any;
  pickcountry?: any;
}
